[tool.pytest.ini_options]
addopts = "-vvv --cov=qrgenerator"
required_plugins = ['pytest-cov>=2.12.1']
log_file = 'logs/pytest-logs.txt'
log_file_date_format = '%Y-%m-%d %H:%M:%S'
log_file_format = '%(asctime)s %(levelname)s %(message)s'
log_file_level = 'DEBUG'
testpaths = ['tests']
python_files = ['test_*.py']
python_functions = ['test_*']
xfail_strict = 'True'

[tool.black]
target-version = ['py36']
include = '\.pyi?$'
exclude = '''

(
    /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.venv
    )/
    |
)
'''