name: Python Black Linting
on: [push]

jobs:

  # Run cleaning process only if workflow is triggered by the non-JetBrains/intellij-platform-plugin-template repository.
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Black Clean-up
        uses: lgeiger/black-action@master
        run: .

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"
      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}